# Generated by Django 4.0.6 on 2022-07-15 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('DOB', models.DateField()),
                ('Adrress', models.CharField(max_length=500)),
                ('Email', models.EmailField(max_length=254)),
                ('Sex', models.CharField(max_length=10)),
                ('Weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('Username', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrentWeight', models.IntegerField()),
                ('TargetWeight', models.IntegerField()),
                ('TargetDate', models.DateTimeField()),
                ('WeeklyRate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('NumberTrainingPerWeek', models.IntegerField()),
                ('BMR', models.DecimalField(decimal_places=2, max_digits=10)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_weight.user')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50)),
                ('Food', models.CharField(max_length=100)),
                ('FoodServing', models.CharField(max_length=150)),
                ('AmountEaten', models.IntegerField()),
                ('CaloriesFoodServing', models.IntegerField()),
                ('CaloriesFood', models.IntegerField()),
                ('TotalCalories', models.IntegerField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_weight.user')),
            ],
        ),
    ]
