# Generated by Django 4.0.6 on 2022-07-19 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_weight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='NumberTrainingPerWeek',
        ),
    ]
