# Generated by Django 2.2.28 on 2022-08-03 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('Adrress', models.CharField(max_length=500)),
                ('Username', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.IntegerField()),
                ('Date', models.DateField()),
                ('Location', models.CharField(max_length=500)),
                ('Photo', models.ImageField(upload_to=None)),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Moneybudget.Category')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Moneybudget.User')),
            ],
        ),
    ]
